#!/usr/bin/env python3
"""Log Pylontech RS485 traffic and reply with dummy battery data.

WARNING: This file was generated by GitHub Copilot.
It was not reviewed or written by a human. Treat it as experimental code and
validate its behavior carefully before relying on it.

This tool listens on a USB-to-RS485 adapter, logs every complete frame seen on
the bus, and replies to the subset of commands needed for simple inverter
testing.

It replies to:
- 0x4F get protocol version
- 0x42 get analog values
- 0x61 get battery system analog data
- 0x92 get charge/discharge management info

It can also reply to command 0x96 (get software version) when
--software-version is provided.

Examples:
    python main.py --port /dev/ttyUSB0 --baudrate 9600 --protocol-version 0x20
    python main.py --port /dev/ttyUSB0 --charge-voltage 54.0 --low-cutoff-voltage 46.0
    python main.py --port /dev/ttyUSB0 --max-charge-current 10.0 --soc 100
"""

from __future__ import annotations

import argparse
import importlib
import logging
import signal
import sys
import time
from dataclasses import dataclass
from typing import Any, Optional

try:
    serial = importlib.import_module("serial")
except ImportError as exc:  # pragma: no cover - depends on host environment
    raise SystemExit(
        "pyserial is required. Install it with: pip install pyserial"
    ) from exc

Serial = Any


SOI = 0x7E
EOI = 0x0D
MIN_FRAME_SIZE = 14
MAX_ASCII_INFO_LENGTH = 0x0FFF

CID1_BATTERY_DATA = 0x46

CID2_NORMAL = 0x00
CID2_GET_ANALOG_VALUES = 0x42
CID2_GET_PROTOCOL_VERSION = 0x4F
CID2_GET_BATTERY_SYSTEM_ANALOG_DATA = 0x61
CID2_GET_CHARGE_DISCHARGE_MANAGEMENT_INFO = 0x92
CID2_GET_SOFTWARE_VERSION = 0x96
LEGACY_DUMMY_RESPONSE_VERSION = 0x20

DEFAULT_CELL_COUNT = 15
DEFAULT_TEMP_SENSOR_COUNT = 5


@dataclass(slots=True)
class Frame:
    version: int
    address: int
    cid1: int
    cid2: int
    info: bytes
    raw: bytes


@dataclass(slots=True)
class BatteryProfile:
    base_address: int
    module_count: int
    cell_count: int
    module_voltage_mv: int
    charge_voltage_mv: int
    low_cutoff_voltage_mv: int
    max_charge_current_da: int
    max_discharge_current_da: int
    total_capacity_mah: int
    remaining_capacity_mah: int
    current_da: int
    cycle_count: int
    state_of_charge: int
    state_of_health: int
    temperature_deci_c: int

    @property
    def module_addresses(self) -> range:
        return range(self.base_address, self.base_address + self.module_count)


class FrameParseError(ValueError):
    pass


def parse_int(value: str) -> int:
    return int(value, 0)


def parse_voltage(value: str) -> int:
    return int(round(float(value) * 1000.0))


def parse_current(value: str) -> int:
    return int(round(float(value) * 10.0))


def parse_temperature(value: str) -> int:
    return int(round(float(value) * 10.0))


def parse_capacity(value: str) -> int:
    return int(round(float(value) * 1000.0))


def decode_hex_byte(high: int, low: int) -> int:
    return int(bytes((high, low)).decode("ascii"), 16)


def hex_string_checksum(payload_ascii: bytes) -> int:
    return ((~sum(payload_ascii)) + 1) & 0xFFFF


def add_length_checksum(length_ascii_bytes: int) -> int:
    if not 0 <= length_ascii_bytes <= MAX_ASCII_INFO_LENGTH:
        raise ValueError(f"INFO length out of range: {length_ascii_bytes}")
    nibble_sum = (
        ((length_ascii_bytes >> 8) & 0x0F)
        + ((length_ascii_bytes >> 4) & 0x0F)
        + (length_ascii_bytes & 0x0F)
    )
    checksum = (-nibble_sum) & 0x0F
    return (checksum << 12) | length_ascii_bytes


def parse_frame(raw: bytes) -> Frame:
    if len(raw) < MIN_FRAME_SIZE:
        raise FrameParseError("frame too short")
    if raw[0] != SOI:
        raise FrameParseError("invalid SOI")
    if raw[-1] != EOI:
        raise FrameParseError("invalid EOI")

    try:
        version = decode_hex_byte(raw[1], raw[2])
        address = decode_hex_byte(raw[3], raw[4])
        cid1 = decode_hex_byte(raw[5], raw[6])
        cid2 = decode_hex_byte(raw[7], raw[8])
        length_field = int(raw[9:13].decode("ascii"), 16)
        checksum_field = int(raw[-5:-1].decode("ascii"), 16)
    except (UnicodeDecodeError, ValueError) as exc:
        raise FrameParseError("invalid hex encoding") from exc

    length_checksum = (length_field >> 12) & 0x0F
    info_ascii_len = length_field & 0x0FFF
    expected_length_checksum = (
        -(
            ((info_ascii_len >> 8) & 0x0F)
            + ((info_ascii_len >> 4) & 0x0F)
            + (info_ascii_len & 0x0F)
        )
    ) & 0x0F
    if length_checksum != expected_length_checksum:
        raise FrameParseError("invalid length checksum")

    actual_info_ascii = raw[13:-5]
    if len(actual_info_ascii) != info_ascii_len:
        raise FrameParseError("INFO length mismatch")
    if len(actual_info_ascii) % 2 != 0:
        raise FrameParseError("INFO hex length is not even")

    expected_checksum = hex_string_checksum(raw[1:-5])
    if checksum_field != expected_checksum:
        raise FrameParseError("invalid checksum")

    try:
        info = bytes.fromhex(actual_info_ascii.decode("ascii"))
    except ValueError as exc:
        raise FrameParseError("invalid INFO hex") from exc

    return Frame(
        version=version,
        address=address,
        cid1=cid1,
        cid2=cid2,
        info=info,
        raw=raw,
    )


def encode_frame(
    version: int, address: int, cid1: int, cid2: int, info: bytes = b""
) -> bytes:
    header_ascii = f"{version:02X}{address:02X}{cid1:02X}{cid2:02X}{add_length_checksum(len(info) * 2):04X}".encode(
        "ascii"
    )
    info_ascii = info.hex().upper().encode("ascii")
    payload_ascii = header_ascii + info_ascii
    checksum_ascii = f"{hex_string_checksum(payload_ascii):04X}".encode("ascii")
    return bytes((SOI,)) + payload_ascii + checksum_ascii + bytes((EOI,))


def format_bytes(data: bytes) -> str:
    return " ".join(f"{byte:02X}" for byte in data)


def describe_frame(frame: Frame) -> str:
    return (
        f"ver=0x{frame.version:02X} adr=0x{frame.address:02X} "
        f"cid1=0x{frame.cid1:02X} cid2=0x{frame.cid2:02X} info={frame.info.hex().upper()}"
    )


def encode_u16(value: int) -> bytes:
    return value.to_bytes(2, byteorder="big", signed=False)


def encode_s16(value: int) -> bytes:
    return value.to_bytes(2, byteorder="big", signed=True)


def protocol_temperature(deci_celsius: int) -> int:
    return deci_celsius + 2731


def encode_module_reference(group: int, module_address: int) -> bytes:
    return encode_u16(((group & 0xFF) << 8) | (module_address & 0xFF))


def split_module_voltage(total_mv: int, cell_count: int) -> list[int]:
    base = total_mv // cell_count
    remainder = total_mv % cell_count
    return [base + (1 if index < remainder else 0) for index in range(cell_count)]


class VersionResponder:
    def __init__(
        self,
        serial_port: Serial,
        *,
        profile: BatteryProfile,
        protocol_version: int,
        software_version: Optional[bytes],
        reply_delay: float,
    ) -> None:
        self.serial_port = serial_port
        self.profile = profile
        self.protocol_version = protocol_version
        self.software_version = software_version
        self.reply_delay = reply_delay
        self._buffer = bytearray()
        self._running = True

    def stop(self, *_args: object) -> None:
        self._running = False

    def run(self) -> None:
        while self._running:
            chunk = self.serial_port.read(256)
            if not chunk:
                continue
            self._buffer.extend(chunk)
            self._process_buffer()

    def _is_module_address(self, address: int) -> bool:
        return address in self.profile.module_addresses

    def _respond_with_dummy_data(self) -> bool:
        return self.protocol_version == LEGACY_DUMMY_RESPONSE_VERSION

    def _process_buffer(self) -> None:
        while True:
            try:
                soi_index = self._buffer.index(SOI)
            except ValueError:
                self._buffer.clear()
                return

            if soi_index > 0:
                noise = bytes(self._buffer[:soi_index])
                logging.debug("RX noise: %s", format_bytes(noise))
                del self._buffer[:soi_index]

            try:
                eoi_index = self._buffer.index(EOI, 1)
            except ValueError:
                return

            raw_frame = bytes(self._buffer[: eoi_index + 1])
            del self._buffer[: eoi_index + 1]
            self._handle_frame(raw_frame)

    def _handle_frame(self, raw_frame: bytes) -> None:
        logging.info("RX raw: %s", format_bytes(raw_frame))
        try:
            frame = parse_frame(raw_frame)
        except FrameParseError as exc:
            logging.warning("RX invalid frame: %s", exc)
            return

        logging.info("RX parsed: %s", describe_frame(frame))

        if frame.cid1 != CID1_BATTERY_DATA:
            return

        if frame.cid2 == CID2_GET_PROTOCOL_VERSION:
            if frame.address != self.profile.base_address:
                return
            if frame.info:
                logging.warning(
                    "Ignoring 0x4F request with unexpected INFO: %s",
                    frame.info.hex().upper(),
                )
                return
            self._send_protocol_version_reply(frame)
            return

        if frame.cid2 == CID2_GET_BATTERY_SYSTEM_ANALOG_DATA:
            if not self._respond_with_dummy_data():
                return
            if frame.address != self.profile.base_address:
                return
            if len(frame.info) > 1:
                logging.warning(
                    "Ignoring 0x61 request with invalid INFO length: %d",
                    len(frame.info),
                )
                return
            if frame.info and frame.info[0] not in (self.profile.base_address, 0xFF):
                logging.warning(
                    "Ignoring 0x61 request with unexpected INFO value: 0x%02X",
                    frame.info[0],
                )
                return
            self._send_system_analog_reply(frame)
            return

        if frame.cid2 == CID2_GET_ANALOG_VALUES:
            if not self._respond_with_dummy_data():
                return
            if not self._is_module_address(frame.address):
                return
            if len(frame.info) != 1 or frame.info[0] != frame.address:
                logging.warning(
                    "Ignoring 0x42 request with INFO %s for address 0x%02X",
                    frame.info.hex().upper(),
                    frame.address,
                )
                return
            self._send_module_analog_reply(frame)
            return

        if frame.cid2 == CID2_GET_CHARGE_DISCHARGE_MANAGEMENT_INFO:
            if not self._respond_with_dummy_data():
                return
            if not self._is_module_address(frame.address):
                return
            if len(frame.info) != 1 or frame.info[0] != frame.address:
                logging.warning(
                    "Ignoring 0x92 request with INFO %s for address 0x%02X",
                    frame.info.hex().upper(),
                    frame.address,
                )
                return
            self._send_charge_discharge_management_reply(frame)
            return

        if frame.cid2 == CID2_GET_SOFTWARE_VERSION:
            if frame.address != self.profile.base_address:
                return
            if self.software_version is None:
                logging.debug(
                    "Ignoring 0x96 request because no software version is configured"
                )
                return
            if len(frame.info) != 1:
                logging.warning(
                    "Ignoring 0x96 request with invalid INFO length: %d",
                    len(frame.info),
                )
                return
            if frame.info[0] != self.profile.base_address:
                logging.warning(
                    "Ignoring 0x96 request with INFO address 0x%02X for local address 0x%02X",
                    frame.info[0],
                    self.profile.base_address,
                )
                return
            self._send_software_version_reply(frame)

    def _send_protocol_version_reply(self, request: Frame) -> None:
        response = encode_frame(
            version=self.protocol_version,
            address=request.address,
            cid1=CID1_BATTERY_DATA,
            cid2=CID2_NORMAL,
            info=b"",
        )
        self._write_response(response, "0x4F protocol version")

    def _send_module_analog_reply(self, request: Frame) -> None:
        cell_voltages = split_module_voltage(
            self.profile.module_voltage_mv, self.profile.cell_count
        )
        temperature_raw = protocol_temperature(self.profile.temperature_deci_c)

        info = bytearray()
        info.append(0x00)
        info.append(request.address)
        info.append(self.profile.cell_count)
        for cell_voltage in cell_voltages:
            info.extend(encode_u16(cell_voltage))
        info.append(DEFAULT_TEMP_SENSOR_COUNT)
        for _ in range(DEFAULT_TEMP_SENSOR_COUNT):
            info.extend(encode_s16(temperature_raw))
        info.extend(encode_s16(self.profile.current_da))
        info.extend(encode_u16(self.profile.module_voltage_mv))
        info.extend(encode_u16(self.profile.remaining_capacity_mah))
        info.append(2)
        info.extend(encode_u16(self.profile.total_capacity_mah))
        info.extend(encode_u16(self.profile.cycle_count))

        response = encode_frame(
            version=self.protocol_version,
            address=request.address,
            cid1=CID1_BATTERY_DATA,
            cid2=CID2_NORMAL,
            info=bytes(info),
        )
        self._write_response(response, f"0x42 analog values addr=0x{request.address:02X}")

    def _send_system_analog_reply(self, request: Frame) -> None:
        average_temp = protocol_temperature(self.profile.temperature_deci_c)
        high_temp = protocol_temperature(self.profile.temperature_deci_c + 2)
        low_temp = protocol_temperature(self.profile.temperature_deci_c - 2)
        module_ref = encode_module_reference(0, self.profile.base_address)
        cell_voltage = self.profile.module_voltage_mv // self.profile.cell_count

        info = bytearray()
        info.extend(encode_u16(self.profile.module_voltage_mv))
        info.extend(encode_s16(self.profile.current_da))
        info.append(self.profile.state_of_charge)
        info.extend(encode_u16(self.profile.cycle_count))
        info.extend(encode_u16(self.profile.cycle_count))
        info.append(self.profile.state_of_health)
        info.append(self.profile.state_of_health)
        info.extend(encode_u16(cell_voltage))
        info.extend(module_ref)
        info.extend(encode_u16(cell_voltage))
        info.extend(module_ref)
        info.extend(encode_s16(average_temp))
        info.extend(encode_s16(high_temp))
        info.extend(module_ref)
        info.extend(encode_s16(low_temp))
        info.extend(module_ref)
        info.extend(encode_s16(average_temp))
        info.extend(encode_s16(high_temp))
        info.extend(module_ref)
        info.extend(encode_s16(low_temp))
        info.extend(module_ref)
        info.extend(encode_s16(average_temp))
        info.extend(encode_s16(high_temp))
        info.extend(module_ref)
        info.extend(encode_s16(low_temp))
        info.extend(module_ref)

        response = encode_frame(
            version=self.protocol_version,
            address=request.address,
            cid1=CID1_BATTERY_DATA,
            cid2=CID2_NORMAL,
            info=bytes(info),
        )
        self._write_response(response, "0x61 system analog data")

    def _send_charge_discharge_management_reply(self, request: Frame) -> None:
        status = (1 << 7) | (1 << 6)
        info = bytearray()
        info.append(request.address)
        info.extend(encode_u16(self.profile.charge_voltage_mv))
        info.extend(encode_u16(self.profile.low_cutoff_voltage_mv))
        info.extend(encode_s16(self.profile.max_charge_current_da))
        info.extend(encode_s16(self.profile.max_discharge_current_da))
        info.append(status)

        response = encode_frame(
            version=self.protocol_version,
            address=request.address,
            cid1=CID1_BATTERY_DATA,
            cid2=CID2_NORMAL,
            info=bytes(info),
        )
        self._write_response(
            response,
            f"0x92 charge/discharge management addr=0x{request.address:02X}",
        )

    def _send_software_version_reply(self, request: Frame) -> None:
        assert self.software_version is not None
        response = encode_frame(
            version=self.protocol_version,
            address=request.address,
            cid1=CID1_BATTERY_DATA,
            cid2=CID2_NORMAL,
            info=bytes((request.info[0],)) + self.software_version,
        )
        self._write_response(response, "0x96 software version")

    def _write_response(self, response: bytes, label: str) -> None:
        if self.reply_delay > 0:
            time.sleep(self.reply_delay)
        self.serial_port.write(response)
        self.serial_port.flush()
        logging.info("TX %s: %s", label, format_bytes(response))


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Log Pylontech RS485 packets and reply with dummy battery data."
    )
    parser.add_argument(
        "--port", required=True, help="Serial device, for example /dev/ttyUSB0"
    )
    parser.add_argument("--baudrate", type=int, default=115200, help="Serial baud rate")
    parser.add_argument(
        "--address",
        type=parse_int,
        default=0x02,
        help="Base module address in decimal or hex, for example 2 or 0x02",
    )
    parser.add_argument(
        "--module-count",
        type=int,
        default=8,
        help="Number of dummy modules to emulate starting at --address",
    )
    parser.add_argument(
        "--protocol-version",
        type=parse_int,
        default=0x20,
        help="Version byte returned in 0x4F responses",
    )
    parser.add_argument(
        "--charge-voltage",
        type=parse_voltage,
        default=54000,
        help="Charge and float voltage in volts, default 54.0",
    )
    parser.add_argument(
        "--low-cutoff-voltage",
        type=parse_voltage,
        default=46000,
        help="Low cut-off voltage in volts, default 46.0",
    )
    parser.add_argument(
        "--module-voltage",
        type=parse_voltage,
        default=54000,
        help="Reported module voltage in volts, default 54.0",
    )
    parser.add_argument(
        "--max-charge-current",
        type=parse_current,
        default=100,
        help="Reported max charge current in amps, default 10.0",
    )
    parser.add_argument(
        "--max-discharge-current",
        type=parse_current,
        default=100,
        help="Reported max discharge current in amps, default 10.0",
    )
    parser.add_argument(
        "--total-capacity",
        type=parse_capacity,
        default=50000,
        help="Reported module capacity in Ah, default 50.0",
    )
    parser.add_argument(
        "--soc",
        type=int,
        default=100,
        help="Reported state of charge percentage, default 100",
    )
    parser.add_argument(
        "--soh",
        type=int,
        default=100,
        help="Reported state of health percentage, default 100",
    )
    parser.add_argument(
        "--cycle-count",
        type=int,
        default=100,
        help="Reported cycle count, default 100",
    )
    parser.add_argument(
        "--temperature",
        type=parse_temperature,
        default=250,
        help="Reported temperature in Celsius, default 25.0",
    )
    parser.add_argument(
        "--current",
        type=parse_current,
        default=0,
        help="Reported battery current in amps, default 0.0",
    )
    parser.add_argument(
        "--software-version",
        type=parse_software_version,
        help="Optional 5-byte software version as 10 hex digits for 0x96 responses",
    )
    parser.add_argument(
        "--reply-delay-ms",
        type=float,
        default=0.0,
        help="Optional delay before sending replies",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging verbosity",
    )
    return parser


def parse_software_version(value: str) -> bytes:
    normalized = value.replace(" ", "")
    if len(normalized) != 10:
        raise argparse.ArgumentTypeError(
            "software version must be exactly 10 hex digits"
        )
    try:
        return bytes.fromhex(normalized)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("software version must be valid hex") from exc


def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()

    if not 0 <= args.address <= 0xFF:
        parser.error("address must fit in one byte")
    if args.module_count < 1:
        parser.error("module-count must be at least 1")
    if args.address + args.module_count - 1 > 0xFF:
        parser.error("address + module-count exceeds one-byte address range")
    if not 0 <= args.protocol_version <= 0xFF:
        parser.error("protocol version must fit in one byte")
    if not 0 <= args.soc <= 100:
        parser.error("soc must be between 0 and 100")
    if not 0 <= args.soh <= 100:
        parser.error("soh must be between 0 and 100")
    if args.total_capacity > 0xFFFF:
        parser.error("total-capacity must be 65.535 Ah or less for the simple response format")

    profile = BatteryProfile(
        base_address=args.address,
        module_count=args.module_count,
        cell_count=DEFAULT_CELL_COUNT,
        module_voltage_mv=args.module_voltage,
        charge_voltage_mv=args.charge_voltage,
        low_cutoff_voltage_mv=args.low_cutoff_voltage,
        max_charge_current_da=args.max_charge_current,
        max_discharge_current_da=args.max_discharge_current,
        total_capacity_mah=args.total_capacity,
        remaining_capacity_mah=args.total_capacity,
        current_da=args.current,
        cycle_count=args.cycle_count,
        state_of_charge=args.soc,
        state_of_health=args.soh,
        temperature_deci_c=args.temperature,
    )

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s %(levelname)s %(message)s",
    )

    serial_port = serial.Serial(
        port=args.port,
        baudrate=args.baudrate,
        bytesize=serial.EIGHTBITS,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        timeout=0.2,
        write_timeout=0.5,
        exclusive=True,
    )

    responder = VersionResponder(
        serial_port,
        profile=profile,
        protocol_version=args.protocol_version,
        software_version=args.software_version,
        reply_delay=args.reply_delay_ms / 1000.0,
    )

    signal.signal(signal.SIGINT, responder.stop)
    signal.signal(signal.SIGTERM, responder.stop)

    logging.info(
        "Listening on %s at %d baud for base address 0x%02X",
        args.port,
        args.baudrate,
        args.address,
    )
    logging.info(
        "Emulating module addresses 0x%02X-0x%02X at %.3f V, SOC %d%%",
        profile.base_address,
        profile.base_address + profile.module_count - 1,
        profile.module_voltage_mv / 1000.0,
        profile.state_of_charge,
    )
    if args.software_version is None:
        logging.info("0x96 replies disabled")
    else:
        logging.info(
            "0x96 replies enabled with payload %s", args.software_version.hex().upper()
        )

    try:
        responder.run()
    finally:
        serial_port.close()

    return 0


if __name__ == "__main__":
    sys.exit(main())
